### ISSUE TITLE
Page overlay sample on macOS

### ISSUE THREAD

**Issue by MartyIX** [drasticactions/Drastic.Tools#1]
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/203266/212066264-f96cdd05-0ca2-4b07-9ccb-729d727f27b7.png">

After the button is clicked:

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/203266/212066313-663e3882-89bb-444c-8be8-fcf4e29a9edd.png">

Is this how it is supposed to work?

**Comment by drasticactions** [comment]
Could you let me know if you compiled this from main? This should be shipping in a nuget later when it is done, AFAIK.

Right now, it's not working, I'm screwing around with it, but I'm unsure if/when it will be done.
